GET http://localhost:4000 HTTP/1.1

###

GET http://localhost:4000/api/adopters?limit=10&sortby=name&sortdir=desc HTTP/1.1

###

GET http://localhost:4000/api/dogs HTTP/1.1

###

GET http://localhost:4000/api/adopters/1/dogs HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}